import Head from "next/head";
import { Lato } from "next/font/google";
import Header from "@/components/Header";
import HomeSection from "@/components/HomeSection";
import AboutSection from "@/components/AboutSection";
import ProjectsSection from "@/components/ProjectsSection";
import ContactSection from "@/components/ContactSection";

const lato = Lato({ subsets: ["latin"], weight: ["300", "400"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Armani.DEV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main
        id="content"
        role="main"
        className={`dark:bg-slate-900 ${lato.className} font-light`}
      >
        <div id="scrollspy">
          <div
            id="home"
            className="max-w-[85rem] h-[calc(100vh-61px)] mx-auto py-10 px-4 sm:px-6 lg:px-8"
          >
            <HomeSection />
          </div>
          {/* <div
            id="about"
            className="max-w-[85rem] h-[calc(100vh-61px)] mx-auto py-10 px-4 sm:px-6 lg:px-8"
          >
            <AboutSection />
          </div> */}
          <div
            id="projects"
            className="max-w-[85rem] h-full mx-auto py-10 px-4 sm:px-6 lg:px-8"
          >
            <ProjectsSection />
          </div>
          <div
            id="contact"
            className="max-w-[85rem] mx-auto py-10 px-4 sm:px-6 lg:px-8"
          >
            <ContactSection />
          </div>
        </div>
      </main>
    </>
  );
}
